#!/bin/bash
export TERM='xterm-256color'
# solarized dir colors
eval `dircolors ~/.dotfiles/dircolors.256dark`

alias c='clear;ls'

# git alias
alias gs='git status'
alias gl='git log'

# vi mode for bash!
set -o vi
